# Generated by Django 3.2.5 on 2023-04-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0003_competition_competition_link_competition_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='The title of the hero to display.', max_length=50, verbose_name='Headline')),
                ('flavor_text', models.CharField(help_text='The flavor text to display below the main headline.', max_length=100, verbose_name='Flavor text')),
                ('is_active', models.BooleanField(help_text='Whether or not this hero should be shown in the homepage carousel.', verbose_name='Show?')),
                ('primary_button_url', models.URLField(blank=True, help_text='Where to link the primary button to.', null=True, verbose_name='Primary button URL')),
                ('primary_button_text', models.CharField(blank=True, help_text='Button text for the primary button.', max_length=25, null=True, verbose_name='Primary button text')),
                ('secondary_button_url', models.URLField(blank=True, help_text='Where to link the second button to.', null=True, verbose_name='Secondary button URL')),
                ('secondary_button_text', models.CharField(blank=True, help_text='Button text for the secondary button.', max_length=25, null=True, verbose_name='Secondary button text')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='home-hero')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='short_desc',
            field=models.CharField(default='This is a short description of the tag.', help_text='A short description of the tag. Also used in meta tags.', max_length=100, verbose_name='Short description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='competition_link',
            field=models.URLField(default='', help_text='Link to competition website.'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='registration_link',
            field=models.URLField(default='', help_text='Registration link.'),
        ),
    ]
