# Generated by Django 3.2.5 on 2023-04-29 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0004_auto_20230429_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagehero',
            name='secondary_button_text',
        ),
        migrations.RemoveField(
            model_name='homepagehero',
            name='secondary_button_url',
        ),
        migrations.AddField(
            model_name='post',
            name='core_tag',
            field=models.ForeignKey(blank=True, help_text='The primary tag to display for this post. Used for vanity only.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='writeups.tag', verbose_name='Core tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.ImageField(blank=True, help_text='The icon to use for this tool.', null=True, upload_to='tag-icons', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='homepagehero',
            name='primary_button_url',
            field=models.URLField(blank=True, help_text='Where to link the primary button to. Make sure you define primary button text, too!', null=True, verbose_name='Primary button URL'),
        ),
    ]
