# Generated by Django 3.2.5 on 2023-04-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0007_post_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='competition_link',
            field=models.URLField(blank=True, help_text='Link to competition website.', null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='registration_link',
            field=models.URLField(blank=True, help_text='Registration link.', null=True),
        ),
    ]
