# Generated by Django 3.2.5 on 2023-04-30 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writeups', '0008_auto_20230430_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='display_as_main_category',
            field=models.BooleanField(default=True, help_text='If checked, this will be listed as one of the main categories on the main writeups listing page. Vanity only.', verbose_name='Display as main category?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
