# Generated by Django 3.2.5 on 2023-05-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0010_alter_post_challenge_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, help_text='The order to display tags in.', null=True, verbose_name='Display order.'),
        ),
    ]
