# Generated by Django 4.1.3 on 2022-12-05 05:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [("writeups", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="content",
            field=tinymce.models.HTMLField(
                help_text="A TinyMCE-driven field for the post content/body copy.",
                verbose_name="Page content",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="content",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="A TinyMCE-driven field for the profile content.",
                null=True,
                verbose_name="Profile content",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="discord_tag",
            field=models.CharField(
                blank=True,
                help_text="Discord tag (with discriminator).",
                max_length=50,
                null=True,
                verbose_name="Discord tag",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="display_name",
            field=models.CharField(
                help_text="Display name used in your URL and in post authoring (if necessary). 35 characters max.",
                max_length=35,
                unique=True,
                verbose_name="Display name",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="use_display_name_in_posts",
            field=models.BooleanField(
                help_text="Whether to use the display name or your full name as the post author.",
                verbose_name="Use display name in posts",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="content",
            field=tinymce.models.HTMLField(
                help_text="A TinyMCE-driven field for the tool's page content.",
                verbose_name="Page content",
            ),
        ),
    ]
