# Generated by Django 4.1.3 on 2022-12-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("writeups", "0003_tag_theme_color")]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="writeups.tag"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tools",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="writeups.tool"
            ),
        ),
    ]
