# Generated by Django 4.1.3 on 2022-12-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("writeups", "0004_alter_post_tags_alter_post_tools")]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="The name used for this tag. 35 characters max.",
                max_length=35,
                primary_key=True,
                serialize=False,
                verbose_name="Tag name",
            ),
        )
    ]
