# Generated by Django 4.1.3 on 2022-12-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("writeups", "0005_alter_tag_name")]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="The name used for this tag. 20 characters max.",
                max_length=20,
                primary_key=True,
                serialize=False,
                verbose_name="Tag name",
            ),
        )
    ]
