# Generated by Django 4.1.3 on 2022-12-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("writeups", "0006_alter_tag_name")]

    operations = [
        migrations.AddField(
            model_name="member",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Special title (e.g. President, Vice President, etc.).",
                max_length=35,
                null=True,
                verbose_name="Title",
            ),
        )
    ]
