# Generated by Django 4.1.3 on 2022-12-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("writeups", "0007_member_title")]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("i", "Individual"), ("t", "Team")],
                default="i",
                help_text="Competition type (individual/team/etc.)",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="vanity_url",
            field=models.SlugField(
                blank=True,
                help_text="The vanity URL (competition/...) - if empty, uses the numerical ID. Use dashes to separate words.",
                null=True,
                unique=True,
                verbose_name="Vanity URL",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="vanity_url",
            field=models.SlugField(
                blank=True,
                help_text="The vanity URL (writeups/...) - if empty, uses the numerical post ID. Use dashes to separate words.",
                null=True,
                unique=True,
                verbose_name="Vanity URL",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="vanity_url",
            field=models.SlugField(
                blank=True,
                help_text="The vanity URL (tool/...) - if empty, uses the numerical ID. Use dashes to separate words.",
                null=True,
                unique=True,
                verbose_name="Vanity URL",
            ),
        ),
    ]
