# Generated by Django 4.1.3 on 2022-12-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writeups", "0008_competition_type_alter_competition_vanity_url_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.SlugField(
                help_text="The name used for this tag. 20 characters max.",
                max_length=20,
                primary_key=True,
                serialize=False,
                verbose_name="Tag name",
            ),
        )
    ]
