# Generated by Django 4.1.3 on 2022-12-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("writeups", "0009_alter_tag_name")]

    operations = [
        migrations.RemoveField(model_name="competition", name="id"),
        migrations.RemoveField(model_name="post", name="id"),
        migrations.RemoveField(model_name="tool", name="id"),
        migrations.AlterField(
            model_name="competition",
            name="vanity_url",
            field=models.SlugField(
                default="undefined-competition",
                help_text="The vanity URL (tool/...). Use dashes to separate words.",
                primary_key=True,
                serialize=False,
                verbose_name="Vanity URL",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="vanity_url",
            field=models.SlugField(
                default="undefined-post",
                help_text="The vanity URL (tool/...). Use dashes to separate words.",
                primary_key=True,
                serialize=False,
                verbose_name="Vanity URL",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tool",
            name="vanity_url",
            field=models.SlugField(
                default="undefined-tool",
                help_text="The vanity URL (tool/...). Use dashes to separate words.",
                primary_key=True,
                serialize=False,
                verbose_name="Vanity URL",
            ),
            preserve_default=False,
        ),
    ]
